keys:
  - &nixpi age184zg0rfghppepg2lkev6hzmauvtz6wnnftkt4uwpdgm8rukm6y7szj7qff
  - &wsl-home age1c6jp48xjdjrsfqmr9afdr45fr7vlvqr9kyqztefjvhsn6jtg0vzsc28att
  - &wsl-work age1te7h62ngk56agqg8raq2le27rscuvvclwe3g906ka7wqarkwwaus7rnwh7
  - &router age18wafdhlw4dxxntdc6qdy9d9dj07hvpf6n8ym3atpq708nx9ycgtsfntz6m
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *nixpi
        - *wsl-home
        - *wsl-work
        - *router

