#!/usr/bin/env bash
printf "%b\n" "/-------------------------------\\"
printf "%b\n" "|         tmux keybinds         |"
printf "%b\n" "\\-------------------------------/"
printf "\n"
printf "%b\n" "/-------------------------------\\"
printf "%b\n" "|            general            |"
printf "%b\n" "|-------------------------------|"
printf "%b\n" "| C-b r cfg hot-reload          |"
printf "%b\n" "| C-b / display hotkeys         |"
printf "%b\n" "| C-b d detach session          |"
printf "%b\n" "|    $ tmux attach -t X         |"
printf "%b\n" "|                               |"
printf "%b\n" "| S-Lclick select text          |"
printf "%b\n" "| S-Rclick paste text           |"
printf "%b\n" "\\-------------------------------/"
printf "\n"
printf "%b\n" "/-------------------------------\\"
printf "%b\n" "|       window navigation       |"
printf "%b\n" "|-------------------------------|"
printf "%b\n" "| C-t   new window              |"
printf "%b\n" "| C-n   next window             |"
printf "%b\n" "| C-p   previous window         |"
printf "%b\n" "| C-b , rename window           |"
printf "%b\n" "| C-b # move to window #        |"
printf "%b\n" "| C-b < swap window left        |"
printf "%b\n" "| C-b > swap window right       |"
printf "%b\n" "\\-------------------------------/"
printf "\n"
printf "%b\n" "/-------------------------------\\"
printf "%b\n" "|        pane navigation        |"
printf "%b\n" "|-------------------------------|"
printf "%b\n" "| C-b hjkl vim pane switching   |"
printf "%b\n" "| C-b C-hjkl vim pane resizing  |"
printf "%b\n" "| C-b [ enter copy mode in pane |"
printf "%b\n" "| C-b z focus current pane      |"
printf "%b\n" "|                               |"
printf "%b\n" "| C-b - split horizontally      |"
printf "%b\n" "| C-b | split vertically        |"
printf "%b\n" "\\-------------------------------/"

