#!/usr/bin/env bash
printf "%b\n" "/-------------------------------\\"
printf "%b\n" "|         tmux keybinds         |"
printf "%b\n" "\\-------------------------------/"
printf "\n"
printf "%b\n" "/-------------------------------\\"
printf "%b\n" "|            general            |"
printf "%b\n" "|-------------------------------|"
printf "%b\n" "| C-b r cfg hot-reload          |"
printf "%b\n" "| C-b ? display hotkey help     |"
printf "%b\n" "| C-b d detach session          |"
printf "%b\n" "|    tmux attach -t X           |"
printf "%b\n" "| S-Lclick select text in tmux  |"
printf "%b\n" "| S-Rclick paste text in tmux   |"
printf "%b\n" "\\-------------------------------/"
printf "\n"
printf "%b\n" "/-------------------------------\\"
printf "%b\n" "|       window navigation       |"
printf "%b\n" "|-------------------------------|"
printf "%b\n" "| C-t   new window              |"
printf "%b\n" "| C-n   next window             |"
printf "%b\n" "| C-p   previous window         |"
printf "%b\n" "| ,     rename window           |"
printf "%b\n" "| C-b x move to window #x       |"
printf "%b\n" "\\-------------------------------/"
printf "\n"
printf "%b\n" "/-------------------------------\\"
printf "%b\n" "|        pane navigation        |"
printf "%b\n" "|-------------------------------|"
printf "%b\n" "| C-b - split horizontally      |"
printf "%b\n" "| C-b | split vertically        |"
printf "%b\n" "| C-b hjkl vim pane switching   |"
printf "%b\n" "| C-b C-hjkl vim resizing       |"
printf "%b\n" "\\-------------------------------/"

