#!/usr/bin/env bash
printf "%b\n" "/-------------------------------\\"
printf "%b\n" "|       window navigation       |"
printf "%b\n" "|-------------------------------|"
printf "%b\n" "| C-t   new window              |"
printf "%b\n" "| C-b & kill current window     |"
printf "%b\n" "| C-b ! break pane to window    |"
printf "%b\n" "|                               |"
printf "%b\n" "| C-b # move to window #        |"
printf "%b\n" "| C-b < swap window left        |"
printf "%b\n" "| C-b > swap window right       |"
printf "%b\n" "|                               |"
printf "%b\n" "| C-b , rename window           |"
printf "%b\n" "| C-b C-= increase font size    |"
printf "%b\n" "| C-b C-- decrease font size    |"
printf "%b\n" "\\-------------------------------/"
printf "\n"
printf "%b\n" "/-------------------------------\\"
printf "%b\n" "|        pane navigation        |"
printf "%b\n" "|-------------------------------|"
printf "%b\n" "| C-b hjkl vim pane switching   |"
printf "%b\n" "| C-b C-arrows pane resizing    |"
printf "%b\n" "| C-b M-arrows pane resizing++  |"
printf "%b\n" "|                               |"
printf "%b\n" "| C-b [ enter copy mode in pane |"
printf "%b\n" "| C-b z focus pane              |"
printf "%b\n" "|                               |"
printf "%b\n" "| C-b space rotate pane layout  |"
printf "%b\n" "| C-b M-# select pane layout    |"
printf "%b\n" "|     M-5 even tiled layout     |"
printf "%b\n" "| C-b C-o rotate panes          |"
printf "%b\n" "|                               |"
printf "%b\n" "| C-b - split pane horizontally |"
printf "%b\n" "| C-b | split pane vertically   |"
printf "%b\n" "|                               |"
printf "%b\n" "| C-b m mark pane               |"
printf "%b\n" "| C-b M-m swap with marked pane |"
printf "%b\n" "| C-b :j    join marked pane    |"
printf "%b\n" "| C-b :j -h join vert. split    |"
printf "%b\n" "\\-------------------------------/"

